### PR TITLE
update docs about config file

### PR DESCRIPTION
**Pull request by M3ssman**
Minor documentation update for configuration file usage

- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by corevo** [comment]
Keep the disabling behavior, some users unbeknownst to them may use a `.sideyml` when they don't want to.

**Comment by M3ssman** [comment]
Current documented option states 

> You can disable that behavior with `--no-sideyml`.  

but that's not true, therefore the update. 
Since Release 3.2.0 (at least) you get an error ```error: unknown option `--no-sideyml'```.
So it's not possible to let side-runner ignore the file if it's named this way.

**Comment by M3ssman** [comment]
Anything new regarding this topic? Or, it's considered a bug when one can't disable the default behavior with that flag?

**Comment by corevo** [comment]
It's definitely a bug, and I should return that flag.

**Pull request closed without merging**
