### PR TITLE
Adding configuration for lock-threads bot [skip ci]

### PR DESCRIPTION
**Pull request by diemol**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by corevo** [comment]
Can we add a label that would stop it from locking a thread?

In case there is an issue that we have confirmed but can't currently resolve?

**Comment by diemol** [comment]
Sorry, I forgot to mention that this will only lock **closed** threads. The idea is to avoid people commenting in old threads instead of opening new issues with reproducible cases.

**Comment by corevo** [comment]
👍

**Comment by corevo** [comment]
Is it enabled for the project?

**Comment by diemol** [comment]
I was just going to ask you that, since I requested it but I don't know who can grant access

image

**Comment by corevo** [comment]
I'm not an owner here, probably @shs96c can do it.

**Comment by corevo** [comment]
Is it working?

**Comment by diemol** [comment]
It is in the docs, docker-selenium and selenium repos, it is locking issues in batches every hour.
And in this repo as well, see for example #691

**Comment by corevo** [comment]
👏

**Pull request merged**
