### PR TITLE
fix issue #1524

### PR DESCRIPTION
**Pull request by giuliohome**
Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium-ide/blob/master/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
The path for chrome driver is wrongly set when starting selenium ide. This is currently a blocking error.

### Motivation and Context
See my [comment there](https://github.com/SeleniumHQ/selenium-ide/issues/1524#issuecomment-1266477370)

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [X] I have read the [contributing](https://github.com/SeleniumHQ/selenium-ide/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by toddtarsi** [comment]
@giuliohome - I wrote a PR migrating from yarn v1 to pnpm this morning. I wanted to know if you'd consider this as an alternative to changing the pathing stuff on that chromedriver executable.

https://github.com/SeleniumHQ/selenium-ide/pull/1528

**Comment by toddtarsi** [comment]
@giuliohome - I like that fix somewhat, but relying on hoisting outside of the package dependencies itself seems a bit hazardous. Pnpm is more up-to-date and consistent with keeping things local here and offers better controls for this. I also like dropping lerna because it has some strange dependencies these days, like Python 3.

**Comment by giuliohome** [comment]
Ok, thank you, I'll try your suggestion, yes maybe pnpm could be good in my scenario, I remember I tried it some times ago and it was good.

**Comment by toddtarsi** [comment]
@giuliohome - Would you try checking out the `switch-to-pnpm` branch and seeing if installing and building via pnpm works for you? I updated the readme as well, but the steps on that branch are this:

```
pnpm -r i; pnpm build; pnpm start;
```

**Comment by giuliohome** [comment]
I'm doing this now... will let you know soon

**Comment by giuliohome** [comment]
Ok, it works (I'd say yarn3 was faster maybe, but... ok).

**Comment by giuliohome** [comment]
**Off Topic**
Excuse me, a question _unrelated_ to yarn3 and pnpm:
I can't export the code when I right click on a test: is this a separate issue to be opened or what?

**Comment by toddtarsi** [comment]
@giuliohome - Yeah, yarn3 might be faster. I'm okay with doing it that way too. The only thing we'd have to do the other way is make sure that asarUnpack thing is updated and works by compiling with `build:electron`. If that isn't in the right place then it doesn't get bundled into the binary and the releases stop working. It was a whole headache trying to get that right.

**Comment by toddtarsi** [comment]
@giuliohome - This is my fault. I am distributing an npm module for it right now:

```
https://npmjs.com/package/@seleniumhq/code-export
```

I have a PR where I was working on folding it into v4 of the IDE still:

https://github.com/SeleniumHQ/selenium-ide/pull/1507

Basically, everything in the IDE pipeline right now is configured to only use typed files and fail on a single type error. 
The problem is that the function shapes here are highly polymorphic and a really bad time to type, and also extremely redundant with the six different modules, so I haven't gotten that working 100% yet from IDE. I have a couple of the language bindings typed, but there's like four or five left to do and such.

**Comment by giuliohome** [comment]
> @giuliohome - Yeah, yarn3 might be faster. I'm okay with doing it that way too. The only thing we'd have to do the other way is make sure that asarUnpack thing is updated and works by compiling with `build:electron`. If that isn't in the right place then it doesn't get bundled into the binary and the releases stop working. It was a whole headache trying to get that right.

I will re-try the whole build with this modification, all from the beginning with git clone (and this change), just to see if this problem is something I can check myself out...

**Comment by toddtarsi** [comment]
@giuliohome - Sounds good. Thanks for calling this out and looking into this. Sorry to run you through this multiple times, I know this part is not fun. For the binary, you'll want to install the matching one for your OS from packages/selenium-ide/dist. It's a bit weird, I had to try to install a couple of them to find the one that worked for my Mac.

Once you find the one that installs right, you'll know it worked if you can load a project at all. Failing to load chromedriver has been wired up to crash things pretty aggressively so I find out from users more quickly.

**Comment by giuliohome** [comment]
These are the commands I have tested again

```bash
rm -rdf selenium-ide/
git clone https://github.com/giuliohome/selenium-ide.git
cd selenium-ide/
git checkout patch-2
yarn set version berry
yarn
yarn build
yarn start
```

It seems all ok to me, but I don't want you accept something that you deem hazardous. Even though I can't see how it would "break the latest binary in alpha", it's not worth taking this risk, if there is this possibility. Feel free to close this PR, no worries. We can really consider this problem closed and resolved. Thank you again

**Comment by toddtarsi** [comment]
Ok, I'll close this for now. Only because checking stuff on the binary is the opposite of a fun time. Thank you for doing these tests. If pnpm gives trouble, I'll keep your fix in mind and come back to go to yarn v3

**Pull request closed without merging**
