### PR TITLE
update chrome options

### PR DESCRIPTION
**Pull request by ionutzp**
- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by corevo** [comment]
Thanks for contributing, currently the documentation is cut from the branch `v3`, in master we are planning on changing the current documentation to meet the requirements of the new electron type IDE.

Can you also add a link to the respective documentation that references these new flags.

**Comment by tourdedave** [comment]
@KoRiGaN Any update on this?

**Comment by rahull** [comment]
[Issue 1786: Feature request: change chromeOptions to goog:chromeOptions](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1786 ) Reference for goog:chromeOptions

**Comment by tourdedave** [comment]
The PR needs to be set against the `v3` branch not `master`.

**Comment by tourdedave** [comment]
Accepting #757 instead since it's committed against the correct branch, and no response received from the OP.

**Pull request closed without merging**
