### PR TITLE
facility for escaping variables in emitted code

### PR DESCRIPTION
**Pull request by kogbill**
### Description

- keep a set of commands that should escape their variables in value parameters
- add an optional argument to `preprocessParameter` and `defaultPreprocessor`
  - the argument is a function to escape values of variables

### Motivation and Context
This is to fix an error which occurs when you use a variable that contains a single quote:

```
      322 | tests["learn base"] = async (driver, vars, opts = {}) => {
      323 |   await driver.wait(until.elementLocated(By.css(`#input-area .cm-content`)), configuration.timeout);
    > 324 |   await driver.findElement(By.css(`#input-area .cm-content`)).then(element => {
          |   ^
      325 |     return driver.executeScript(`if(arguments[0].contentEditable === 'true') {arguments[0].innerHTML = '${vars.name}'}`, element);
      326 |   });
      327 |   await driver.wait(until.elementLocated(By.css(`#input-area .cm-content`)), configuration.timeout);
```
### Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [X] I have read the [contributing](https://github.com/SeleniumHQ/selenium-ide/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

**Note: I am unable to run the tests because of (at least) this error:**

```
project file is too old for the runner, upgrade the project via the IDE
```

My changes work when I hack them into `selianize.cjs.js` though and run tests on our own code.

### CODE REVIEW

**Comment by kogbill** [comment]
This should allow easy fixing of this issue: https://github.com/SeleniumHQ/selenium-ide/issues/1240

Note that quotes in variables work from the IDE, just not with WebDriver.

This only fixes quotes in variables that are in the `escapeVarsInValue` set. Right now `editContent` is the only member of that set but more commands can be added to it.

This does not address quotes locators -- there is no way to escape quotes in xpath but maybe it's possible to restructure certain expressions to use concat, [like so](https://stackoverflow.com/a/57639969/1026782).

**Comment by toddtarsi** [comment]
@kogbill - I am so sorry this took so long, but all of that slash juggling looks about right. Could you merge the latest in here? I'd like to merge everything I can to try and get caught up on PRs.

**Comment by toddtarsi** [comment]
@kogbill - I am closing this PR, but I have cherry-picked your hard work here and the commit is still in your name (or @zot):

https://github.com/SeleniumHQ/selenium-ide/pull/1297

Thank you both again.

**Comment by zot** [comment]
Thanks! (from my personal account)

**Pull request closed without merging**
