### PR TITLE
189 Add multi select, multi copy and multi paste

### LINKED ISSUE #189: copy/cut/paste multiple commands
When I write tests, I often find the need to break apart my complex creations into more manageable chunks. Is there a way to copy/cut/paste multiple commands between tests?  This would be an awesome add.

### PR DESCRIPTION
**Pull request by carlos-granados**
- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

Fixes #189

I think that the functionality described in that issue is pretty fundamental. Being able to choose several steps to copy and paste is a must, otherwise sharing steps between tests is just a huge pain if you have to do it one by one

This code is based on the work already done by @Jongkeun in https://github.com/SeleniumHQ/selenium-ide/pull/241, so many thanks to him. I just did two things:
- Modify the code to match the new prettier linting rules
- Fix several small issues which were preventing this code from running correctly

I have tested it extensively and seems to be working fine, any feedback welcome

This not only allows you to copy/paste steps within a test, it allows you to copy them to a new test or even a new project

### CODE REVIEW

**Review by corevo — CHANGES_REQUESTED** [review]
The top border on the selected commands is there to denote where in the test new recorded commands will enter.

Make sure that only that single command is the one that has the highlighted blue border.

Thanks for contributing this, many people have asked for a long time for this.

**Comment by Richisfree** [comment]
@corevo @carlos-granados Just wondering if this pull request will be merged??  Seems like a lot of people what the functionality and it's all but ready to go??  Thanks in advance.

**Comment by carlos-granados** [comment]
@RichardHaynes @corevo unfortunately I did not find the time to finish this PR and I am no longer working on this so I don't think I can pick it up again. Hopefully someone can pick this up and finish it

**Comment by Richisfree** [comment]
Hi @corevo this looks so close to finished, what's the recommended process here to progress this should I want to?  
1. Branch @carlos-granados's commit, pull in the current default branch and try to resolve the border formatting issue?  
2. Somehow contribute to @carlos-granados's branch to progress his change request? 
3. Other?

**Comment by toddtarsi** [comment]
@carlos-granados - Closing this, as multi select is deeply implemented, albeit poorly tuned, in v4.

**Comment by carlos-granados** [comment]
LOL, I had completely forgotten about this. Good luck with it!

**Comment by toddtarsi** [comment]
Thank you for your contributions and the well-wishes @carlos-granados!

**Pull request closed without merging**
