### PR TITLE
fix #1417 - include project name in window title

### LINKED ISSUE #1417: Include project file name in project title bar
image
Would be helpful to see active SIDE file name in title bar

### PR DESCRIPTION
**Pull request by coinzdude**
Include project title in project editor and initial playback window

### CODE REVIEW

**Comment by coinzdude** [comment]
fixed with d4f538dc38ccffda6db9d29c7a93360c439930f3

**Comment by coinzdude** [comment]
While this appears to work fine, I have a concern on this PR, 

packages\selenium-ide\src\main\session\controllers\Playback\index.ts , line 50
```            playbackWindow.getTitle().startsWith(title) &&
```

I'm not able to use breakpoints at the moment, but my assumption since this used to be === title, that title was "Playback Window" but now I'm not sure about this matching rule here.

**Comment by toddtarsi** [comment]
@coinzdude - Fair critique, I think the issues here have been addressed 🙂 

Let me know if I can help elsewhere here

**Comment by toddtarsi** [comment]
@coinzdude - Closing this PR, as project name is in window title in latest I think

**Pull request closed without merging**
