### PR TITLE
(fix):  fix for generateMethodDeclaration override

### PR DESCRIPTION
**Pull request by matewilk**
**Thanks for contributing to the Selenium IDE!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium-ide/blob/master/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

Fix for the issue described here https://github.com/SeleniumHQ/selenium-ide/issues/1619#issuecomment-1540105040

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium-ide/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by toddtarsi — APPROVED** [review]
LGTM 👍 Nice addition @matewilk - Thank you for the help, you are one in a milli

**Comment by toddtarsi** [comment]
@matewilk - Cool to merge or want me to wait for anything?

**Comment by matewilk** [comment]
Yeah, it's not ready to be merged, I've updated the description, I still need your eyes on it if possible, I have a feeling it's not the proper solution + typescript complains.
If you could take a look at it and left some comments for me to address that would be amazing 🙏

**Comment by matewilk** [comment]
@toddtarsi  let me know if you are able to leave some comments over the weekend.

**Comment by matewilk** [comment]
I have a gut feeling this should be addressed somewhere else in the code, but not sure where, I'm not familiar enough with the codebase yet

**Comment by matewilk** [comment]
Ok, I've fixed the typescript issue, I've tested it manually and it seems to be working, I've tried running tests on my local but seems they are failing massively so not sure whether I need to worry about it @toddtarsi

Please take a look and approve when you have a chance. Cheers!

**Comment by toddtarsi** [comment]
@matewilk - I can definitely review code. It's just writing it thats the hard part. Thank you for taking this on

**Comment by matewilk** [comment]
Hey @toddtarsi
Are you happy to merge this one please?

**Comment by toddtarsi** [comment]
@matewilk - This LGTM 👍

**Comment by toddtarsi** [comment]
@matewilk - can you increment version on side-code-export and rerun `pnpm i -r` and commit those?

**Comment by matewilk** [comment]
Let me know if this is what you were after @toddtarsi

**Review by toddtarsi — APPROVED** [review]
@matewilk - This is perfect (and thank you for updating local refs, this is exactly it). Thank you sir, merging!

**Pull request merged**
