### PR TITLE
beta v7 release candidate

### PR DESCRIPTION
**Pull request by toddtarsi**
## **User description**
@fernandozw - I took your code and am teeing this up as the next release candidate! I tried to keep the core things involving the language maps, but I switched out openBrowser for a modified version of requestPlaybackWindow (this way it works with the tab system).

Please test with me and let me know your thoughts!

___

## **Type**
enhancement, bug_fix

___

## **Description**
- Added extensive language maps for UI elements to support both English and Chinese translations.
- Introduced new components and API commands for handling language settings and displaying messages.
- Enhanced `requestPlaybackWindow` to accept an optional URL for improved flexibility.
- Various code cleanup and formatting adjustments across multiple files for better readability and maintenance.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><details><summary>8 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>I18N.ts</strong><dd><code>Add Language Maps for UI Elements</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
packages/selenium-ide/src/browser/enums/I18N.ts

<li>Added extensive language maps for UI elements in both English and <br>Chinese.<br> <li> Included translations for window tabs, menu trees, configuration tabs, <br>and more.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium-ide/pull/1816/files#diff-6e6ccd4ae9150222279d1e4dc41464fe4a42b3dbd2444b7aefe4452d4ab828bd">+2176/-0</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>Message.tsx</strong><dd><code>Add New Message Component for Alerts</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
packages/selenium-ide/src/browser/windows/ProjectEditor/tabs/Project/Message.tsx

<li>Introduced a new component for displaying messages using MUI Snackbar <br>and Alert.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium-ide/pull/1816/files#diff-bca1cc168ccee9fc5da98399adc2558ca91acea423826eb5f2b34a997812e616">+39/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>OutPutSettings.tsx</strong><dd><code>Implement Output Settings Component with Export Functionality</code></dd></summary>
<hr>
      
packages/selenium-ide/src/browser/windows/ProjectEditor/tabs/Project/OutPutSettings.tsx

<li>Added a new component for output settings with functionality to export <br>tests.<br> <li> Implemented language map support for dynamic translations.<br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium-ide/pull/1816/files#diff-0b927d72887f7b24ae6ddb5aea289d74e00e61fe2b24044be2eb72ca13186562">+320/-0</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>index.ts</strong><dd><code>Enhance requestPlaybackWindow to Accept URL</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
packages/selenium-ide/src/main/session/controllers/Windows/index.ts

- Modified `requestPlaybackWindow` to optionally accept a URL.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium-ide/pull/1816/files#diff-75f3d7b053c3987b58e3e3bcdaf86040b4156c060f57f939898c306745178ef3">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>getLanguage.ts</strong><dd><code>Add API Command to Get Language Setting</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
packages/side-api/src/commands/system/getLanguage.ts

- Introduced a new API command to get the current language setting.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium-ide/pull/1816/files#diff-d713296d459e10e5a190965e4b697b32ad5fd684943582810d499de71cc85bff">+4/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>getLanguageMap.ts</strong><dd><code>Add API Command to Retrieve Language Map</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
packages/side-api/src/commands/system/getLanguageMap.ts

<li>Added a new API command to retrieve the language map for translations.<br> <br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium-ide/pull/1816/files#diff-db69ca81a85fd1224f3d43841204dc8c47939545ae17165466f57c7b45d03984">+4/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>setLanguage.ts</strong><dd><code>Add API Command to Set Language</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
packages/side-api/src/commands/system/setLanguage.ts

- Added a new API command to set the current language.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium-ide/pull/1816/files#diff-5d0f2ece39a23cccb21eb46752906a566399d6fc1f0b5af12584d45939a5b44f">+4/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>requestPlaybackWindow.ts</strong><dd><code>Update requestPlaybackWindow Command to Accept URL</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
packages/side-api/src/commands/windows/requestPlaybackWindow.ts

- Updated the command to optionally accept a URL parameter.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium-ide/pull/1816/files#diff-ec4e1c69295917edefcd95a08752fc9b55fa9f8d2d8c5ddfc8fb566b7b5a9b67">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Error handling
</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>find-select.ts</strong><dd><code>Improve Error Handling in find-select.ts</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
packages/selenium-ide/src/browser/windows/PlaybackWindow/preload/find-select.ts

<li>Added comments to catch block within <code>processElementAtCommand</code> function.<br> <br>

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium-ide/pull/1816/files#diff-6a7df9980d81fb35e7b5b8fda9c2364c7fd66b5cc7f53000f99e3662f77116c0">+3/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Formatting
</strong></td><td><details><summary>4 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>prompt.ts</strong><dd><code>Code Cleanup in prompt.ts</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
packages/selenium-ide/src/browser/windows/PlaybackWindow/preload/prompt.ts

- Minor formatting adjustments and cleanup.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium-ide/pull/1816/files#diff-dba319197006099412a56679f3bc6ee331b64fc36f16c751dfe12b9fae856846">+1/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>record-handlers.ts</strong><dd><code>Fix Import Formatting in record-handlers.ts</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
packages/selenium-ide/src/browser/windows/PlaybackWindow/preload/record-handlers.ts

- Imported `locatorBuilders` with correct spacing.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium-ide/pull/1816/files#diff-1eac3e3671fb01c2da26ef37cb9f8768ccd0b175b0a90fe7ec8b47d1147b94d7">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>record-shortcuts.ts</strong><dd><code>Formatting Adjustment in record-shortcuts.ts</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
packages/selenium-ide/src/browser/windows/PlaybackWindow/preload/record-shortcuts.ts

- Corrected spacing for `targets` assignment.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium-ide/pull/1816/files#diff-77badb0e4216922e42ff64ed3873a408b03c8981f68d539f0dbc4174f3a198e2">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>utils.ts</strong><dd><code>Improve Readability of isVisible Function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
packages/selenium-ide/src/browser/windows/PlaybackWindow/preload/utils.ts

- Reformatted the `isVisible` function for better readability.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium-ide/pull/1816/files#diff-4e86c8d4f79cb26f4d99208555fc69187b0d23f0ae72d9c236fc25a09289cd08">+37/-24</a>&nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Bug fix
</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>index.ts</strong><dd><code>Adjust Development Mode Check</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
packages/selenium-ide/src/main/session/controllers/System/index.ts

- Adjusted development mode check to exclude production environment.

</details>
    

  </td>
  <td><a href="https://github.com/SeleniumHQ/selenium-ide/pull/1816/files#diff-4dbd893211cc75242de37cef110ee13c64879374f43a7a94be947eacbc059bb2">+2/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by toddtarsi** [comment]
@fernandozw - I am going to merge this in just a bit. It resolves an issue where the system.onLog api causes another system.onLog api that continues until the whole system crashes.

**Comment by fernandozw** [comment]
Okay, I will pull the latest version for testing tomorrow. Thank you for your hard work.

**Comment by fernandozw** [comment]
@toddtarsi I just used the beta-v7-preview branch to build&start, and found that there is no language selection option function and output function. Do I need to complete these functions on the beta-v7-preview branch?

选择语言

**Comment by toddtarsi** [comment]
Ah! Let me cherry pick it across real quick!

**Comment by toddtarsi** [comment]
@fernandozw - Oh my gosh, I had a ton in my stash. Sorry about the delay. Changes should be here now. Holy cow, you really worked hard on the codebase. 💪 Nice job!!!!

**Comment by toddtarsi** [comment]
@fernandozw - Oh, I think I messed up some of the localization around deleting suites. I am sorry, but the component structure has changed a lot there and I may have goofed that a bit. Regardless, I think I got most of the items brought across. From here, we can probably do smaller PRs to fix. Nice job again!!!

**Comment by toddtarsi** [comment]
@fernandozw - For some of these "OutPut" options, is there any chance you'd want to add that functionality via a plugin? It seems like you're wanting to integrate a testing platform into the IDE, which I absolutely love. However, I want to keep the vanilla UX and base platform as simple as possible and support enriched UX via plugins like most IDEs do. Would it be cool if I rewrite some of that UX later into a "testing platform" plugin type of thing?

**Comment by toddtarsi** [comment]
For now, I'm going to merge it with that panel. But later, I'd like to make that panel into a plugin so it can kind of really get into that logic without making the base IDE more confusing.

Also, I'm disabling the ide-runner test for now. Something has changed in github actions and it's wasted two days of my time 😡

**Comment by fernandozw** [comment]
@toddtarsi I think it is a very good idea to connect to the test platform in the form of a plug-in, which will not destroy the original core functions of selenium ide.

**Comment by fernandozw** [comment]
@toddtarsi It doesn’t matter, open source projects themselves require a long period of reconstruction and accumulation in usage scenarios. A good project must go through a lot of consideration and demonstration. This is why I like the tool selenium ide, because there are almost 10 Over the years, this project has been iterating on new features

**Comment by toddtarsi** [comment]
@fernandozw - 💯 I feel the same. Some time soon, I will transplant this UX into the example plugin in side-example-suite, so it can hopefully act as a guide for plugin authors to inject custom pages or components into the app in a way that plays nicely with the panel system and such.

**Comment by toddtarsi** [comment]
My api for client side plugin UX is not complete, but it has a good bit of work. There is an event emitter `api.plugins.onRequestCustomEditorPanel.dispatchEvent` that appends webframes to the editor window, but I think it's not stateful enough. I think we need to make 2 new functions in side-api:

```
api.plugins.registerCustomPanel(
    type: 'config-settings-group', // where this panel goes and how its labeled (maybe other options are test-editor and tab?)
    name: 'OutPut' // Must be global unique
    url: 'file://' + path.join(__dirname, 'client/settings-panel.html')
)
api.plugins.getCustomPanels(
    type: 'config-settings-group' | 'test-interface'
)
```

**Comment by fernandozw** [comment]
I haven’t studied the plug-in yet🤦‍♂️. I will familiarize myself with the working principle of the plug-in as soon as possible. I think the electron version of selenium ide is much more perfect in terms of working method and ease of use than previous browser plug-ins. Regarding plug-in functions, It will make selenium ide more convenient to connect with external tools or platforms,👍

**Comment by fernandozw** [comment]
@toddtarsi So I developed the output function on selenium ide (sorry, this destroyed the core function of selenium ide. Now it seems that it is the most reasonable to exist in the form of a plug-in), using the data of the session file of selenium ide, imported into Test the platform, store all data in the database, make persistence, and execute it on the test platform. Haha, my idea is that the UI automated test is completely closed-loop. The test engineer only needs to record the test case, and all subsequent regression tests are left to the test platform. The core of ci/cd is that we write and debug use cases, all on selenium, because it is so convenient. I don’t care at all how to execute the subsequent test cases. After importing to the test platform, the test platform will be based on the settings Scheduled tasks or pull requests of business systems are run because I just want to reduce the time spent maintaining test cases, because I am a very lazy person😄

**Comment by toddtarsi** [comment]
@fernandozw - Thank you so much for your help with the code. I am very impressed with how effective you are at working in the codebase. I will work on adding a plugin with debug rendering panels to [this directory](
https://github.com/SeleniumHQ/selenium-ide/tree/trunk/packages/side-example-suite/src/plugins/custom-click
)

**Pull request merged**
