### PR TITLE
Save last selected command per test to prevent the need to rescroll

### PR DESCRIPTION
**Pull request by dvd900**
I added the field selectedCommand to the TestState which I set in selectCommand. When a new test is selected, I check to see if that field is set and use if set.

Test pass the same as in Master, Lints with no errors. 

For the proposed feature:
https://github.com/SeleniumHQ/selenium-ide/issues/510

- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by dvd900** [comment]
As a note: the reason why I had to do the scroll in test Row instead of test table was because the test row's mount occurs after the test table update.

**Comment by dvd900** [comment]
Is there something more to be done for this?

**Comment by corevo** [comment]
I'm on vacation this week, I'll review it next work week

**Comment by corevo** [comment]
Thanks for contributing ❤️

**Pull request merged**
