### PR TITLE
Migrate old Selenium IDE test suites

### LINKED ISSUE #84: loading old Suits in Selenium IDE
Hey guys,
maybe I am too stupid, but I am not able to load my old selenium testsuits? Adding old cases works fine ..
cheers
thanks for your great work

### LINKED ISSUE #95: How to load old selenium test suite with new selenium IDE for chrome
I have old selenium test suite (HTML) which have many other test cases (html). Now, i am trying to migrate them to new selenium ide .  I could see opening old test suite is not there. Everything is changed to project and extension of files are  (.side). Can please guide us the steps to open our old test suite in new selenium IDE for chrome.

Even after creating new project in new IDE i can add empty test suite and empty test case but how can i add old html test case content to new test case in new ide. (Not even copy paste is possible)
It is not straight forward or not even given a workaround of loading old suite or html files. please guide us.

### LINKED ISSUE #114: Issue handling &quot; from old ide scripts
It appears version 1.0.3 has an issue with how old selenium id stored the html equivilant to quotes for locators.

`css=input[name=&quot;login&quot;]`

2018-0227-v1 0 3-issuewithquotes

### PR DESCRIPTION
**Pull request by corevo**
Will be included in v1.0.4
Fixes #95 
Fixes #84
Fixes #114

### CODE REVIEW

**Comment by brentrug** [comment]
So is it now possible to open old projects from 2.9 like discussed here:
https://github.com/SeleniumHQ/selenium-ide/issues/95

**Comment by corevo** [comment]
Yes, if you're having issues with the migration process, don't hesitate to open an issue.

**Comment by brentrug** [comment]
Hi Tomer,

is still wonder, how i can convert old selenium ide 2.9.1 test cases & suites into new selenium:

https://github.com/SeleniumHQ/selenium-ide/issues/95 <https://github.com/SeleniumHQ/selenium-ide/issues/95>

Can you help?

**Comment by corevo** [comment]
Just open the suite in the new IDE and follow the import wizard.

**Comment by brentrug** [comment]
I'm now working on Chrome 67 and Selenium IDE 3.1.0 and i can't not even select the old (html) test suite, as you can see on the screenshot (all grayed out). Those are tests made in selenium 2.9.1

bildschirmfoto 2018-07-26 um 14 14 00

**Comment by corevo** [comment]
What's the file extension you're trying to open?

**Comment by brentrug** [comment]
The file have no extension, as you can see in the printscreen.

The content of the test case looks like that:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="http://localhost/sakkadentrainer/" />
<title>seite</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">seite</td></tr>
</thead><tbody>
<tr>
	<td>storeEval</td>
	<td>{new Date()}</td>
	<td>Cur_time</td>
</tr>
<tr>
	<td>open</td>
	<td>${www}/home.${usr_lang}.html</td>
	<td></td>
</tr>


```

And the test case:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta content="text/html; charset=UTF-8" http-equiv="content-type" />
  <title>Test Suite</title>
</head>
<body>
<table id="suiteTable" cellpadding="1" cellspacing="1" border="1" class="selenium"><tbody>
<tr><td><b>Test Suite</b></td></tr>
<tr><td><a href="set_vars_de">set_vars_de</a></td></tr>
<tr><td><a href="login_susu">login_susu</a></td></tr>
```

**Comment by corevo** [comment]
Add `htm/html` file extension

**Comment by brentrug** [comment]
Wow... Thanks a lot. Finally it works :D Now i just have to change all the commands, which are not working anymore... :(

**Comment by corevo** [comment]
@OleanderRose can you upload the suite? don't need the actually test cases.

**Comment by OleanderRose** [comment]
[testsuite.txt](https://github.com/SeleniumHQ/selenium-ide/files/2310345/testsuite.txt)

**Comment by OleanderRose** [comment]
okay. I understand. I had problems to upload the testsuite here in the blog as log as the files were pgp encrypted. So I uploaded you the unencrypted version. But: The testsuite I originally use is pgp encrypted, which is transparent to most of the products, but not for the selenium IDE. Do you have an idea how selenium could work also with pgp encrypted files?

**Comment by OleanderRose** [comment]
The problem is another. I can import the testsuite, if it is stored on drive c:
I cannot import the testsuite, if it is store on drive o:
Is it possible, that the SeleniumIDE project importer cannot work with network drives?

**Comment by corevo** [comment]
signed or encrypted? the distinction is important.  
Also I don't see a reason why we won't be able to load files from network drives, I don't have any nfs available, I'll have to see when I get the time to test this.

**Comment by OleanderRose** [comment]
the import of the file works when loaded from c:. So the drive is the important thing.

**Comment by OleanderRose** [comment]
is there a documentation or anothe issue, where it is described how to migrate the old test suites, i.e. why the variables do not work: 
command1: store a b 
command2: echo ${b}
the ${b} does not read the variable define before.

**Comment by shibleemehdi** [comment]
Hi, both 'Test Suite' and 'Test Cases' has to be with html extension to open and migrate?

**Comment by nylemenon** [comment]
> 
> 
> I am trying to load old Selenium test suites using IDE v3.4.4. I open an old suite and the wizard says I need to add all of the test files listed, which I do. It then drops back to a blank Selenium IDE window and hangs there. Not sure how to get around this...
 

I have the same issue as tdmiller, was it resolved? The screen moz-extension:// just stays blank.

**Comment by corevo** [comment]
@nylemenon @tdmiller Can you open an issue with a reproducer?

**Pull request merged**
