### PR TITLE
(feat): nr synthetics exporter initial commit

### PR DESCRIPTION
**Pull request by matewilk**

### CODE REVIEW

**Comment by matewilk** [comment]
Sorry @toddtarsi,

My bad, I should have create this PR against my forked trunk. I'll close this PR but also wanted to ask you for help regardless.

I can move it to our conversation - https://github.com/SeleniumHQ/selenium-ide/issues/1605

So this PR contains a new exporter which exports only one command `click` (`emitClick`).

I just want to see if I set everything up correctly, but when I'm trying running tests from the root dir with:
```sh
pnpm run test --testMatch "**/packages/code-export-js-newrelic-synthetics/**/*.spec.js"
```

I'm getting the following error:
```sh
> selenium-ide-monorepo@ test /Users/mwilk/Workspace/New Relic Synthetics Exporter/selenium-ide
> jest "--testMatch" "**/packages/code-export-js-newrelic-synthetics/**/*.spec.js"

 FAIL  packages/code-export-js-newrelic-synthetics/__test__/src/index.spec.js
  ● Test suite failed to run

    packages/code-export-js-newrelic-synthetics/src/index.ts:6:8 - error TS2307: Cannot find module 'side-code-export' or its corresponding type declarations.

    6 } from 'side-code-export'
             ~~~~~~~~~~~~~~~~~~

Snapshot Summary
 › 1 snapshot file obsolete from 1 test suite. To remove it, run `npm test -- -u`.
   ↳   • packages/side-runtime/__tests__/__snapshots__/recording-syncronizer.spec.js.snap

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   1 file obsolete, 0 total
Time:        5.278 s
Ran all test suites.
 ELIFECYCLE  Test failed. See above for more details.
```

I also tried the approach from your `side-example-suite` with generating an output with:
```json
"build:code": "side-code-export ./dist/index.js ./projects/plugin.side ./tests",
```

But I'm encountering the same issue:
```sh
➜ pnpm run build:code                                                                    

> code-export-js-newrelic-synthetics@4.0.0-alpha.2 build:code /Users/mwilk/Workspace/New Relic Synthetics Exporter/selenium-ide/packages/code-export-js-newrelic-synthetics
> side-code-export ./dist/index.js ./projects/plugin.side ./tests

sh: side-code-export: command not found
```

So it seems like that after merging with the latest `trunk` where you had moved from `@seleniumhq/side-code-export` to `side-code-export` I can't get the test running properly.

I tried a few config changes both in `jest.config.js` and various `tsconfig.json` files but I can't get things working.
It is as if `jest` was unable to link `side-code-export` from `ts` files with the package.

How were you able to run your test with:
```json
"build:code": "side-code-export ./dist/formats/custom-python.js ./projects/plugin.side ./tests",
```

You must have a proper setup for the file to be generated under `tests` directory.

Are you able to share the secret? :)

**Comment by toddtarsi** [comment]
Oh! I bet I know the issue, let me take a peek real quick 😄

**Comment by toddtarsi** [comment]
After you added your new package / workspace, did you reinstall everything with `pnpm i -r`?

**Comment by toddtarsi** [comment]
Also, I intend to boost up the tooling here so that you don't have to fork in the future. I would love it if you were able to write the nr-synthetics-exporter without having to fork things, and can instead just import side-code-export as a dependency for the necessary types and tooling, and then you could just publish it on npm as like `side-code-export-nr-snythetics-exporter` or whatever.

**Comment by matewilk** [comment]
Same thing I'm afraid:

I just did `pnpm i -r` from the root
```sh
➜ pnpm i -r
.                                        |  WARN  Unsupported engine: wanted: {"node":"16.x"} (current: {"node":"v18.15.0","pnpm":"8.0.0"})
packages/selenium-ide                    |  WARN  Unsupported engine: wanted: {"node":"16.x"} (current: {"node":"v18.15.0","pnpm":"8.0.0"})
Scope: all 23 workspace projects
Lockfile is up to date, resolution step is skipped
 WARN  Failed to create bin at /Users/mwilk/Workspace/New Relic Synthetics Exporter/selenium-ide/packages/code-export-csharp-commons/node_modules/.bin/side-code-export. The source file at /Users/mwilk/Workspace/New Relic Synthetics Exporter/selenium-ide/packages/side-code-export/dist/bin.js does not exist.
 WARN  Failed to create bin at /Users/mwilk/Workspace/New Relic Synthetics Exporter/selenium-ide/packages/code-export-csharp-xunit/node_modules/.bin/side-code-export. The source file at /Users/mwilk/Workspace/New Relic Synthetics Exporter/selenium-ide/packages/side-code-export/dist/bin.js does not exist.
 WARN  Failed to create bin at /Users/mwilk/Workspace/New Relic Synthetics Exporter/selenium-ide/packages/code-export-csharp-nunit/node_modules/.bin/side-code-export. The source file at /Users/mwilk/Workspace/New Relic Synthetics Exporter/selenium-ide/packages/side-code-export/dist/bin.js does not exist.
 WARN  7 other warnings
Done in 2.2s
```

But running tests throws the same thing
```sh
➜ pnpm run test --testMatch "**/packages/code-export-js-newrelic-synthetics/**/*.spec.js"
 WARN  Unsupported engine: wanted: {"node":"16.x"} (current: {"node":"v18.15.0","pnpm":"8.0.0"})

> selenium-ide-monorepo@ test /Users/mwilk/Workspace/New Relic Synthetics Exporter/selenium-ide
> jest "--testMatch" "**/packages/code-export-js-newrelic-synthetics/**/*.spec.js"

 FAIL  packages/code-export-js-newrelic-synthetics/__test__/src/index.spec.js
  ● Test suite failed to run

    packages/code-export-js-newrelic-synthetics/src/index.ts:6:8 - error TS2307: Cannot find module 'side-code-export' or its corresponding type declarations.

    6 } from 'side-code-export'
             ~~~~~~~~~~~~~~~~~~

Snapshot Summary
 › 1 snapshot file obsolete from 1 test suite. To remove it, run `npm test -- -u`.
   ↳   • packages/side-runtime/__tests__/__snapshots__/recording-syncronizer.spec.js.snap

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   1 file obsolete, 0 total
Time:        4.454 s
Ran all test suites.
 ELIFECYCLE  Test failed. See above for more details.
```

**Comment by matewilk** [comment]
I also did `pnpm rebuild`

```sh
pnpm rebuild                                                                           
 WARN  Unsupported engine: wanted: {"node":"16.x"} (current: {"node":"v18.15.0","pnpm":"8.0.0"})
node_modules/.pnpm/@bazel+hide-bazel-files@1.7.0/node_modules/@bazel/hide-bazel-files: Runninode_modules/.pnpm/@bazel+hide-bazel-files@1.7.0/node_modules/@bazel/hide-bazel-files: Running postinstall script, done in 99ms
node_modules/.pnpm/@bazel+typescript@5.6.0_typescript@4.8.4/node_modules/@bazel/typescript: node_modules/.pnpm/@bazel+typescript@5.6.0_typescript@4.8.4/node_modules/@bazel/typescript: Running postinstall script, done in 92ms
node_modules/.pnpm/@bazel+jasmine@5.6.0_jasmine-core@4.4.0_jasmine@4.4.0/node_modules/@bazelnode_modules/.pnpm/@bazel+jasmine@5.6.0_jasmine-core@4.4.0_jasmine@4.4.0/node_modules/@bazel/jasmine: Running postinstall script, done in 85ms
```

But nothing has changed

**Comment by toddtarsi** [comment]
@matewilk - I see some things where pnpm is really not happy with some bin stuff, which kinda makes sense to occur in normal land, but not here where we are building after install. Can you build (to make bin for side-code-export), run `pnpm i -r` (to copy bin to expected location), and then try the CLI command again?

**Comment by toddtarsi** [comment]
Also I see some engine complaints, and I have not checked pnpm v8 and node v18 yet. This might come down to needing pnpm v7 and/or node 16. v8 is still really new and I had to set back our major version to use v7 last week

**Comment by matewilk** [comment]
Ok, I've done that and got a different error now, so there's progress 😃 

```sh
➜ pnpm run test --testMatch "**/packages/code-export-js-newrelic-synthetics/**/*.spec.js"
 WARN  Unsupported engine: wanted: {"node":"16.x"} (current: {"node":"v18.15.0","pnpm":"8.0.0"})

> selenium-ide-monorepo@ test /Users/mwilk/Workspace/New Relic Synthetics Exporter/selenium-ide
> jest "--testMatch" "**/packages/code-export-js-newrelic-synthetics/**/*.spec.js"

 FAIL  packages/code-export-js-newrelic-synthetics/__test__/src/index.spec.js
  ● Test suite failed to run

    packages/code-export-js-newrelic-synthetics/src/command.ts:8:22 - error TS2307: Cannot find module 'location' or its corresponding type declarations.

    8 import location from 'location'
                           ~~~~~~~~~~

Snapshot Summary
 › 1 snapshot file obsolete from 1 test suite. To remove it, run `npm test -- -u`.
   ↳   • packages/side-runtime/__tests__/__snapshots__/recording-syncronizer.spec.js.snap

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   1 file obsolete, 0 total
Time:        5.113 s
Ran all test suites.
 ELIFECYCLE  Test failed. See above for more details.
 ```

**Comment by matewilk** [comment]
Got it working, there are some errors sill, but I should be good from here

Thanks a lot!

**Comment by matewilk** [comment]
By the way, once I'm done with the project, would you be ok to merge it to this codebase?

**Comment by toddtarsi** [comment]
That's a good question! In truth, I don't want to merge it into the codebase. That effort would hamper both of us long term. Instead, I want to enable the following flow to be as optimized as possible:

1. You decide to be the language / framework owner of the new relic export.

2. You write a format like you did, but instead of doing it from within the codebase, you do it from a standalone Github repo, using the side-code-export package provided via NPM or Yarn to help with the types and maybe do tests and stuff. I should make a boilerplate generator for this. It would not be too hard I don't think, and I'd be happy to try. Wooing you with fine tooling is a big part of my goal.

3. You publish your repo, and you publish your own NPM package (side-code-export-nr-snythetics-exporter). I believe doing this would make it where you could export your test suites right now by doing the following commands:

```
npm install -g side-code-export
npm install -g side-code-export-nr-snythetics-exporter
side-code-export  side-code-export-nr-snythetics-exporter ./projects/*.side ./nr-tests
new-relic ./nr-tests/*;
```

And I think this is already better, because now you're already exporting and tweaking the format without my say-so.

4. You ping me here, and I post it on the README.md file as the first community written export format.

5. Over the next two years, I [continue to lean fully into the functionality of code-export](https://docs.google.com/presentation/d/1B4l6Tz1IZFOhCQq54wEiM4q3upAhOoMrgwK5qqdZ2gA/edit?usp=sharing). You let me know what pain points you see. A big one for me is upgrading the strings in JS to files with handlebar templates. I'd like all JS to disappear from formats with time. Language preference is antithetical to this tooling imo.

6. When people have nr specific questions, they ping you as the format owner, rather than me, who knows very little.

**Comment by matewilk** [comment]
I kind of knew the answer but was worth giving it a try :)

This makes a lot of sense.

So my current understanding is that I just need two packages to be able to eject this to a separate repo and everything should be working as it is now:
- [side-code-export](https://www.npmjs.com/package/side-code-export)
- [side-model](https://www.npmjs.com/package/@seleniumhq/side-model)

Additionally:
- typescript config
- jest config
- etc 
but these have no hard requirements as long as my project compiles into `dist` with `index.js`

And I should be good to go.

I'm seeing a lot of other configs in the main repo like babel, prettier, some references to webpack and I'm assuming those are related to the monorepo and how it builds and manages all the packages tests builds etc.

Are there any other dependencies I should take into consideration before moving it to a separate repo?

**Comment by matewilk** [comment]
The end goal here is to be able to run it along with the [selenium-ide browser extension](https://chrome.google.com/webstore/detail/selenium-ide/mooikfkahbdckldjjndioackbalphokd?hl=en) and export recorded tests to NR Synthetics format.

**Comment by toddtarsi** [comment]
@matewilk - Oh no, v3!?! I am sorry, this is for v4. v3 is a real son of a bitch to modify or extend. You basically have to write and publish a webextension to talk to the v3 webextension and provide the output format programatically. The export format is largely the same, just no types.

Here is the v3 source:

https://github.com/SeleniumHQ/selenium-ide/tree/v3

I can't in good conscience advocate the plugin approach for v3 because its so much complexity.

**Comment by matewilk** [comment]
This is the thing, I need to be able to integrate the New Relic exporter with the selenium recorder.

Or at least provide a browser extension that people can use but the requirement here is to be able to record their tests by visiting a website and record their journeys. Obviously the preference is to use v4, but you're saying that the Selenium IDE browser extension was discontinued?

So this format is not compatible with the recorder? It should be, right? as long as it's just a dist index file, I should be able to plug it into the recorder.

**Comment by matewilk** [comment]
Oh yeah, via a browser extension, but it should all work together just fine

**Comment by matewilk** [comment]
Correct me if 'm wrong but my assumption is:
- [Selenium IDE recorder](https://chrome.google.com/webstore/detail/selenium-ide/mooikfkahbdckldjjndioackbalphokd?hl=en) spits out a format like [this](https://github.com/SeleniumHQ/selenium-ide/blob/trunk/packages/side-example-suite/projects/plugin.side)
- I write a browser extension to plug this with my exporter
- when I request to export via the Selenium (v3) browser extension the [recorded format](https://github.com/SeleniumHQ/selenium-ide/blob/trunk/packages/side-example-suite/projects/plugin.side) is being put through my New Relic exporter (browser extension) and at the end I'm able to save the exported (.js) file with New Relic formatted code.

Until there is an easier way of doing that?

**Comment by toddtarsi** [comment]
Yes. For exactly your case, v3 had this documentation on plugin writing:

https://www.selenium.dev/selenium-ide/docs/en/plugins/code-export

**Comment by toddtarsi** [comment]
It holds up, and its valid. Basically, you'd do that, and then publish that webext to the stores, and any browser with both selenium IDE and your plugin will automagically see nr code export here.

Personally, I hate this paradigm. Plugins should be per project, not per browser imo. But it does work.

**Comment by matewilk** [comment]
Good to know I'm still on the right track 😄 

I totally agree, but it is what it is 🤷 

I might ping you again in a separate issue, eventually.

I'm closing this PR, thanks a lot for all the input! Much appreciated.

**Comment by toddtarsi** [comment]
Yes, and in v4, my goal is to remove this and instead operate on npm as the publish target since its so much easier, and we don't need to consume an api to provide stuff running native. I hope you're around for a while.

**Comment by matewilk** [comment]
Yes, I'll be sticking around for sure, I'm going to get my New Relic extension/exporter to the end line for sure

**Pull request closed without merging**
