### PR TITLE
Integrate SideeX with selenium-ide

### PR DESCRIPTION
**Pull request by corevo**
[SideeX](https://github.com/SideeX/sideex) is a good starting point

### CODE REVIEW

**Comment by manoj9788** [comment]
we hold off merging this until we get approval from SFC?

**Comment by corevo** [comment]
Indeed, I'm just putting this as WIP

**Comment by bcmoney** [comment]
I was the one who contacted SideeX team, is the Selenium team planning/able to ok using some of the project, cherry-pick some specific commits, or just use it as a reference? They were generous enough to jump in so just wondering as this PR got closed...

**Comment by corevo** [comment]
We closed it as we await licensing approval, once it's approved we'll reopen the PR

**Comment by zavelevsky** [comment]
OK to ignore Travis warnings as it's not really set to perform any actual tests

**Pull request merged**
