### PR TITLE
Solving "DataCloneError: The object could not be cloned" on save

### PR DESCRIPTION
**Pull request by ygmarchi**
**Thanks for contributing to the Selenium IDE!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium-ide/blob/master/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium-ide/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by corevo** [comment]
Please fix the linting errors.

**Review by toddtarsi — APPROVED** [review]
LGTM 👍

**Comment by toddtarsi** [comment]
Oh wait, I think the spaces before the parens would cause linter failures.

**Comment by toddtarsi** [comment]
Screw it I'll fix the linter later, thanks again for this @ygmarchi

**Pull request merged**
