### PR TITLE
feat(plugin): send save instead of emit for save action

### PR DESCRIPTION
**Pull request by zewa666**
related issue  https://github.com/SeleniumHQ/selenium-ide/issues/607

- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by zewa666** [comment]
@corevo and @tourdedave as discussed in the related topic, how about we send a specialized emit action type called `save`, so that plugins can handle this case accordingly. Moreover this would simplify the documentation of the workaround needed for the current Chrome issue

**Comment by corevo** [comment]
This is a breaking change for the API, and unless we draft API v2, I don't think we can change it at this point.  
This will probably have to be fixed through documentation instead.

**Comment by zewa666** [comment]
So I've looked through the source and it seems like the combination of `emit` and `project` is used only for the save dialog scenario. Is that right? If so, yeah that can be handled via documentation only. Waiting for your reply then I'll create the docs PR

**Comment by zewa666** [comment]
closing in favour of https://github.com/SeleniumHQ/selenium-ide/pull/617

**Pull request closed without merging**
