### PR TITLE
Fix `wait_for_window` output when exporting Ruby code

### PR DESCRIPTION
**Pull request by lusingander**
**Thanks for contributing to the Selenium IDE!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium-ide/blob/master/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description

If we export tests with `waitForWindow` to Ruby, it's grammatically incorrect.

- Method definitions are the same as in Python.
- Close block `}` is missing.

### Motivation and Context

#917 

(This PR solves some of the problems with #917, but not all. "Error 3" in this issue seems to be very different.)

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium-ide/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
  - update snapshot
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by toddtarsi — APPROVED** [review]
LGTM 👍

Yeah, item 3 is certainly interesting. I didn't even know those could be generated like that. Very interesting!

**Review by diemol — APPROVED** [review]
Thanks for reviewing, @toddtarsi!

**Comment by diemol** [comment]
Congrats on your first contribution, @lusingander!

**Comment by lusingander** [comment]
thank you 🙂

**Pull request merged**
