### PR TITLE
closes SeleniumHQ#1637 - fixed selenium side runner issue in windows

### PR DESCRIPTION
**Pull request by ghost**
Selenium side runner not working in windows machine 

### Description
Regarding issue #1637  fix is working fine in Windows machine . 

### Motivation and Context
This change will fix selenium side runner to run in windows machine .
image

### Types of changes
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [x ] I have read the [contributing](https://github.com/SeleniumHQ/selenium-ide/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

This change does not require a test case as it is a change in the command line.

### CODE REVIEW

**Comment by toddtarsi** [comment]
DUDE=! This is so huge. You rock! I appreciate it this so much. I'm going to approve and merge this, and cycle out a new version of the runner. Thank you!

**Comment by toddtarsi** [comment]
Oh @mrgamedev07 - Can you try and sign this license stuff? Idk how it works but I'd love to merge this and take it out

**Comment by mrgamedev07** [comment]
@toddtarsi , license stuff is done ,one more check is failed because of test cases .some test case is getting failed not sure why .In my windows machine "pnpm run test" itself is not working .I think it is configured to run in mac /linux ?

**Comment by toddtarsi** [comment]
@mrgamedev07 - I think that's a test that needs to use localhost instead of google because it gets kinda intermittent. I'm going to rerun the job a couple times. If it fails three times in sequence, sure. But this change should either make everything fail or nothing fail I feel like.

**Comment by toddtarsi** [comment]
If it passes, we'll just merge and I'll dogear those tests to look at another time

**Comment by toddtarsi** [comment]
Nah I'm merging this thats some don't use google for your e2e test type stuff

**Pull request merged**
