### PR TITLE
WIP: Serialize Selenium IDE code into CLI executable webdriver code

### LINKED ISSUE #66: CLI executing
Are there any plans for executing on Command Line Interface with Selenium IDE TNG?
I think we already have some plans like below:

* plan 1: feature of exporting WebDriver code with some general languages.
* plan 2: `.side` format test runner "selenium-side-runner.jar" like selenium-html-runner.jar
* plan 3: something new and smart plan I don't know :)

### PR DESCRIPTION
**Pull request by corevo**
Fixes #66

### CODE REVIEW

**Comment by Naramsim** [comment]
Hi, thanks to have implemented this functionality, can you please upload a newer release containing this changes to Github? The last release of Selenium IDE do not contains them.

**Comment by corevo** [comment]
Yes, I will post a pre-release version to GitHub containing this

**Comment by mike741** [comment]
Hi, first of all, THANK YOU for picking this project back up! Second, I've downloaded the Beta linked to yesterday, have recorded a sequence of commands, and have clicked the "Export to Javascript Code" button. However, upon opening the exported JS file it appears to be empty aside from some basic templating. Is this expected behavior at the moment?

**Comment by corevo** [comment]
Not at all, can you please attach the test you tried to export?

Cheers,
Tom

**Comment by Naramsim** [comment]
Moreover, the crx you uploaded is marked as 'broken' by Chrome

**Comment by mike741** [comment]
Sure thing. Here's a screenshot. On the right are the test commands, on the left is the JS script that I exported to.

screen shot 2018-01-24 at 6 19 54 pm


Let me know if you need more info.

**Comment by corevo** [comment]
@Naramsim as of chrome 63, installing .crx not from the store will result in it being marked corrupted.  
You will to load the sources as a developer.

**Comment by corevo** [comment]
@mike741 I was able to recreate the problem and will work on a fix

**Comment by Naramsim** [comment]
I'm using version 1.03 pulled from Chrome webstore, but I don't see any button to export the code

**Comment by Jongkeun** [comment]
@Naramsim , The button you mentioned for exporting the code is this?

image

**Comment by corevo** [comment]
@Naramsim It's not completed yet, there is another pr on the way.  
You can access it by having a development build.

**Comment by corevo** [comment]
Hey all, I've published a new release with some fixes, including the one reported by @mike741  
You can check it out [here](https://github.com/SeleniumHQ/selenium-ide/releases/tag/v1.1.0-beta.2).  
Sadly you still have to install it as developer on chrome.  
Since this PR is closed I'd like to move all conversations to #131

**Pull request merged**
