### PR TITLE
Update command.js

### PR DESCRIPTION
**Pull request by ThibaudLopez**
corrected quotes, see https://github.com/SeleniumHQ/selenium-ide/issues/824

- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by tourdedave** [comment]
Hey @ThibaudLopez, thanks again! Please fix the linting error.

**Comment by ThibaudLopez** [comment]
Hi @tourdedave, which linting error? jslint does not give me an error. Do you mean the missing semicolon at the end? It wasn't there before. I can add it, but it's unrelated to the Issue. Please let me know. Thanks.

**Comment by tourdedave** [comment]
It comes from ESLint when you run `yarn lint`. See [here](https://travis-ci.com/SeleniumHQ/selenium-ide/jobs/239534105#L683).

**Comment by ThibaudLopez** [comment]
Hi @tourdedave, I fixed the linting error. Please try again. Thanks

**Comment by mattonem** [comment]
Hi @tourdedave,
I can see that this contribution was approved and merged to the main project, yet it seems it didn't made its way to the released version. 
Was that on purpose? Was it reverted a some point? Any good reason not to have this fix in the main project?
I'm facing this issue as the side-runner replaces my json double quote by single quote when I run script and this contribution would save my day. 
Thanks.

**Pull request merged**
