### PR TITLE
updated download-driver.ts null ref to fix build on windows, refresh dependencies

### PR DESCRIPTION
**Pull request by coinzdude**
**Thanks for contributing to the Selenium IDE!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium-ide/blob/master/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ x] I have read the [contributing](https://github.com/SeleniumHQ/selenium-ide/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by toddtarsi** [comment]
@coinzdude - Oh shit, you've found my branch haha 😓 . Can you make this PR against my running-v4-without-v3 branch in origin? That way the diff is a lot less bad. Thank you so much for contributing!

**Comment by toddtarsi** [comment]
Also, I'll try and merge my stuff to trunk asap so we can work off of there. Thank you so much for helping me from the Windows side! I've been solely on Mac up until now and so there's a lot that may be wrong, and I'm really sorry for that, but hey, you're here now!!! 😄

**Comment by toddtarsi** [comment]
@coinzdude - I just merged everything from that PR to trunk, so if you could pull trunk in here now, the diff will be so much better, and I'll review it ASAP. Thanks again for being here!!!

**Comment by coinzdude** [comment]
Will do! Thanks!

**Comment by toddtarsi** [comment]
@coinzdude - Hey, can I ask what version of NodeJS you're using? I've been building on 14, and I'd like to enforce parity here using the engines flag, and basically I'd be cool with using a different version too, but I'd like to source a second opinion for what node version others are using. Especially someone using Windows, since I feel like some of the earlier versions were much worse on Windows.

**Comment by toddtarsi** [comment]
@coinzdude - For expediency, I cherry-picked your commit directly and merged it in a PR here:

https://github.com/SeleniumHQ/selenium-ide/pull/1348

For clarity, you keep full authorship of your commit. I am just committing it in directly to eschew any rebase work. I'll close this PR, and thank you for your hard work.

**Pull request closed without merging**
