### PR TITLE
Updated Python code export command emitters that use ActionChains to …

### PR DESCRIPTION
**Pull request by PhilGreen**
…use argument self.driver

Was using just driver which resulted in NameError exception when executing the exported code.
Fix for issue https://github.com/SeleniumHQ/selenium-ide/issues/826

- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by seanpoulter** [comment]
I'm biased because:
- I'm unfamiliar with the repo
- I haven't run the code
- I work with @PhilGreen 

These changes look sound. I've reviewed the instances of `driver` in both files and they look good. 👍 

While you're in there @PhilGreen, how about fixing these two instance of `Webself.driver` which should be `Webdriver`:
- [ ] https://github.com/SeleniumHQ/selenium-ide/blob/c4463c48db1a7ee0071fa44e509eb9cdfff482ed/packages/code-export-python-pytest/__test__/src/__snapshots__/command.spec.js.snap#L285
- [ ] https://github.com/SeleniumHQ/selenium-ide/blob/c4463c48db1a7ee0071fa44e509eb9cdfff482ed/packages/code-export-python-pytest/src/command.js#L680-L684

**Comment by PhilGreen** [comment]
Thanks @seanpoulter I added a commit (https://github.com/SeleniumHQ/selenium-ide/pull/827/commits/17d2e085b19e6661a7e6a20d5ea404901437a9c7) that fixes the typo.

**Comment by PhilGreen** [comment]
hmm build failed but it appears it might be CI infrastructure related

**Comment by tourdedave** [comment]
Thanks! 👏

**Pull request merged**
