### PR TITLE
V3

### PR DESCRIPTION
**Pull request by spatel-37**
- [x] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by corevo** [comment]
The IDE as  a webextension is developed in the v3 branch, while the new electron based one is developed on master.  
They are committed on the correct branch, further releases of the IDE and the runner will be cut from v3 rather than master.

**Comment by spatel-37** [comment]
I’m unable to install selenium-ide-3.5.11. Attempted yarn build but received error:
lerna ERR! yarn run build exited 2 in 'selenium-ide-extension'
lerna ERR! yarn run build stdout:
$ rm -rf build && env NODE_ENV=production webpack
[copy-webpack-plugin] WARNING - unable to locate '../selenium/selenium-core-scripts/selenium-browserdetect.js'

Please can you help with instructions to install v3.5.11?

Thanks

Sanjay Patel

Trainee Application Support Analyst

IT Services

[Title: Phone - Description: Phone]

+44 (0) 1274 233616


[Title: Mobile - Description: Mobile]

+44 (0) 07827976477


[Title: Web Address - Description: Web Address]

www.bradford.ac.uk

**Comment by corevo** [comment]
Switch to the branch v3 and follow the build instructions on that branch.

**Comment by spatel-37** [comment]
Hi Tomer, I attempted the build instructions for branch v3 on my Ubuntu 18.04 box but getting this error:

$yarn build selenium-ide
lerna ERR! yarn run build exited 127 in '@seleniumhq/side-commons'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 127.

Any ideas?

Many thanks

Sanjay


Sanjay Patel

Trainee Application Support Analyst

IT Services

[Title: Phone - Description: Phone]

+44 (0) 1274 233616


[Title: Mobile - Description: Mobile]

+44 (0) 07827976477


[Title: Web Address - Description: Web Address]

www.bradford.ac.uk

**Comment by spatel-37** [comment]
I also attempted just the yarn command but received this error:

warning eslint-config-klopov > eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
/bin/sh: 1: npm: not found
error Command failed with exit code 127.
Process stalled
Active handles:
  - Socket
  - Socket
  - Socket
  - TLSSocket

lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in 'selenium-side-runner'
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.

Sanjay

Sanjay Patel

Trainee Application Support Analyst

IT Services

[Title: Phone - Description: Phone]

+44 (0) 1274 233616


[Title: Mobile - Description: Mobile]

+44 (0) 07827976477


[Title: Web Address - Description: Web Address]

www.bradford.ac.uk




From: Sanjay Patel
Sent: 01 April 2019 16:26
To: 'SeleniumHQ/selenium-ide' <reply@reply.github.com>
Subject: RE: [SeleniumHQ/selenium-ide] V3 (#639)

Hi Tomer, I attempted the build instructions for branch v3 on my Ubuntu 18.04 box but getting this error:

$yarn build selenium-ide
lerna ERR! yarn run build exited 127 in '@seleniumhq/side-commons'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 127.

Any ideas?

Many thanks

Sanjay


Sanjay Patel

Trainee Application Support Analyst

IT Services

[Title: Phone - Description: Phone]

+44 (0) 1274 233616



[Title: Mobile - Description: Mobile]

+44 (0) 07827976477



[Title: Web Address - Description: Web Address]

www.bradford.ac.uk<http://www.bradford.ac.uk>

**Pull request closed without merging**
