### PR TITLE
Add plugin support to the IDE

### PR DESCRIPTION
**Pull request by corevo**
more info and rough api soon

### CODE REVIEW

**Comment by Liptoon** [comment]
Hi,
I want to develop a custom localtor plugin. 
Would this be possible with the coming plugin support?
And is there any progress?

**Comment by corevo** [comment]
Yes, adding new locator types is part of the scope, see #104 
Currently no, the current roadmap is
- flow control (e.g. if, while, do etc...)
- code export to run from CI
- extensions

I really hope I could get back on this soon

**Comment by Jongkeun** [comment]
I'm curious.
Let me know what this is for.

**Comment by Jongkeun** [comment]
@corevo 
27e71af was  commited.
Did you do it intentionally? It just dummy.

**Comment by corevo** [comment]
@Jongkeun it was intentional, I was gonna add a new tab anyway, and I gave you feedback yesterday.  
I felt like adding it my way will just help you add yours.

**Pull request merged**
