### PR TITLE
We should use appropriate asserts.

### PR DESCRIPTION
**Pull request by mattonem**
It makes better exception message and more accurate assertions.

**Thanks for contributing to the Selenium IDE!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium-ide/blob/master/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have read the [contributing](https://github.com/SeleniumHQ/selenium-ide/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by toddtarsi — APPROVED** [review]
LGTM 👍 

Let me know if you'd like to take this out of draft and I'll approve it. This sort of thing looks like a nice QOL bump

**Comment by toddtarsi** [comment]
@mattonem - This looks good. The only thing holding me back from merging and releasing this is that it's marked as a draft currently. That seems deliberate. Let me know when you're ready, and I'd be happy to review and likely merge. The only reason I'm writing this message tbh is on the off-chance you're wondering why I haven't merged this 🙂

**Comment by toddtarsi** [comment]
@mattonem - Bumpy bump. I just wanted to check in here and ask, would you want to merge this? I really appreciate PRs like this, but its still marked as a draft, so I'm just checking in haha. Thanks again for contributing!

**Comment by mattonem** [comment]
@toddtarsi oh sorry I missed all the previous notification. 
Sure I want to merge this. 
It is not unit tested though... Do you trust my code regardless?

**Comment by mattonem** [comment]
@toddtarsi just removed the draft tag. Cause I have no idea how to write unit tests to assert the type of message return by assertions...

**Comment by toddtarsi** [comment]
@mattonem - Yes. I am still working on adding test coverage back for code export. And yes, I trust you, or someone else will hopefully PR to fix later

**Comment by mattonem** [comment]
@toddtarsi sounds great. So feel free to merge this contribution. Thanks for the review.

**Pull request merged**
