### PR TITLE
fix:ide delete test case fail

### PR DESCRIPTION
**Pull request by smildlzj**
when delete any test case, cause error. console will print error message.

reproduce step like that

1. new project,
2. add some test case
3. delete it
4. cause error......

image
```
TypeError: Cannot read properties of undefined (reading 'id')
    at mutator (E:\workspace\webfront\selenium-ide\packages\selenium-ide\build\webpack:\side-api\src\commands\tests\delete.ts:34:35)
    at doAPI (E:\workspace\webfront\selenium-ide\packages\selenium-ide\build\webpack:\src\main\api\classes\Handler.ts:56:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at IpcMainImpl.<anonymous> (E:\workspace\webfront\selenium-ide\packages\selenium-ide\build\webpack:\src\main\api\classes\Handler.ts:65:22)
```
this is my debug stack
image

because `newTestIndex` isn't correct, so fix it.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium-ide/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by toddtarsi** [comment]
@smildlzj - Ah! It makes me so happy to see more PRs from you. I have a similar request to last time, although I see you're already ahead of me on the side-api version. Nice!!!

Can you increment the version of @seleniumhq/side-api [here](https://github.com/SeleniumHQ/selenium-ide/blob/trunk/packages/selenium-ide/package.json#L103) to match the dependency to your increment in the side-api package, and then increment the version [here](https://github.com/SeleniumHQ/selenium-ide/blob/trunk/packages/selenium-ide/package.json#L3) so that we get a new binary out with your fix?

**Comment by smildlzj** [comment]
> @smildlzj - Ah! It makes me so happy to see more PRs from you. I have a similar request to last time, although I see you're already ahead of me on the side-api version. Nice!!!
> 
> Can you increment the version of @seleniumhq/side-api [here](https://github.com/SeleniumHQ/selenium-ide/blob/trunk/packages/selenium-ide/package.json#L103) to match the dependency to your increment in the side-api package, and then increment the version [here](https://github.com/SeleniumHQ/selenium-ide/blob/trunk/packages/selenium-ide/package.json#L3) so that we get a new binary out with your fix?

ok，does https://github.com/SeleniumHQ/selenium-ide/blob/trunk/packages/selenium-ide/package.json#L3 version need increase?

**Comment by toddtarsi** [comment]
@smildlzj - Yep! That's how the system knows to make a new binary. Otherwise, it doesn't bother. Every package except the selenium-ide kicks out a new npm version on increment, and selenium-ide makes a new github release on increment.

**Comment by smildlzj** [comment]
> @smildlzj - Yep! That's how the system knows to make a new binary. Otherwise, it doesn't bother. Every package except the selenium-ide kicks out a new npm version on increment, and selenium-ide makes a new github release on increment.

done

**Review by toddtarsi — APPROVED** [review]
@smildlzj - Nice work as always! Thanks and merging!

**Pull request merged**
