### PR TITLE
improvement: filter element is not visible

### PR DESCRIPTION
**Pull request by smildlzj**
### Description

```
<div style="width: 40px; height: 20px;">
  <input type="checkbox" class="yun-switch-checkbox">
</div>
```
```
.yun-switch-checkbox {
    position: absolute;
    left: 0;
    top: 0;
    opacity: 0;
    z-index: 1;
    width: 100%;
    height: 100%;
    cursor: pointer;
}
```
image

when html and style like that，will cause step fail, because element is not visible.   

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium-ide/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by toddtarsi** [comment]
@smildlzj - Interesting! So, you're tweaking the locator builder to skip 0 opacity elements? Very cool!

**Comment by toddtarsi** [comment]
@smildlzj - lgtm, can you do me a favor?

Can you increment the version here:

https://github.com/SeleniumHQ/selenium-ide/blob/trunk/packages/selenium-ide/package.json#L3

Doing that means this'll kick off a new release when merged

**Comment by smildlzj** [comment]
> @smildlzj - Interesting! So, you're tweaking the locator builder to skip 0 opacity elements? Very cool!

@toddtarsi  yes. in my case,  just skip 0 opacity.  and version has increased.

**Review by toddtarsi — APPROVED** [review]
LGTM 👍 Thanks for the great contribution and happy hacktober!!!

**Pull request merged**
