### PR TITLE
selenium-side-runner support multiple nested capabilities

### PR DESCRIPTION
**Pull request by bolasblack**
For example:

```bash
selenium-side-runner -c "
  browserName='chrome'
  screener.name='My Chrome Test'
  screener.resolution='1280x1024'
  screener.apiKey='xxx'
  screener.group='xxx'
"
```

- [X] By placing an `X` in the preceding checkbox, I verify that I have signed the [Contributor License Agreement](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#step-6-sign-the-cla)

### CODE REVIEW

**Comment by bolasblack** [comment]
@corevo Sorry, I didn't noticed the tests files

I have added the new test

**Comment by corevo** [comment]
Run the prettifier and I'll merge 🐢

**Comment by bolasblack** [comment]
@corevo It's so weird, seems my editor's auto format function broken...

I have formatted the code now :P

**Comment by corevo** [comment]
Thanks 🐢

**Pull request merged**
