### PR TITLE
Accessibility fix ( long test names can be scrolled into view )

### PR DESCRIPTION
**Pull request by MarkoMackic**
### Description

If test names overflow parent container in x direction, container will be scrollable.

### Motivation and Context

I want to see long test names....

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium-ide/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by MarkoMackic** [comment]
Not yet working ..

**Comment by MarkoMackic** [comment]
Now it's working..

**Comment by MarkoMackic** [comment]
Partial #987 fix.

**Comment by tourdedave** [comment]
@MarkoMackic can you fix the linting error?

**Comment by MarkoMackic** [comment]
Sure :)

**Pull request merged**
