### PR TITLE
Typo in assert interface

### PR DESCRIPTION
**Pull request by mattonem**
**Thanks for contributing to the Selenium IDE!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium-ide/blob/master/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium-ide/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by mattonem** [comment]
Interface doc: https://nodejs.org/api/assert.html#assertequalactual-expected-message

**Review by toddtarsi — APPROVED** [review]
LGTM 👍

**Comment by toddtarsi** [comment]
@mattonem - Can you increment the version of the code-export-javascript-mocha package? That way it publishes a new version to npm so you can use it right away?

**Comment by mattonem** [comment]
@toddtarsi done. 
Fun story, I must have introduced this bug myself, but I just realised that my project was not pointing to the good code base. And I had tested another version of the code... Hence, I broke the mocha exporter for everyone months ago without ever being affected by it.

**Comment by toddtarsi** [comment]
@mattonem - I do it all the time, that's why I'm working on more tests for the ide runtime 😆 😬

**Pull request merged**
