### PR TITLE
Export emitCommand from export-code

### PR DESCRIPTION
**Pull request by pierrekin**
**Thanks for contributing to the Selenium IDE!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium-ide/blob/master/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
Simply export the functions which code-export on a 'per command' basis.

### Motivation and Context
I have already made and merged a PR for the selianize package, which does the same thing.

Please see the PR here. https://github.com/SeleniumHQ/selenium-ide/pull/538

The motivation is the same, I am working on a project which needs to translate side commands to selenium webdriver commands with more control than what is possible with the 'test-suite' generation style.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium-ide/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by corevo — CHANGES_REQUESTED** [review]
Please add a test for the new emitCommand function.

**Comment by avoid3d** [comment]
Hey team, sorry for the extremely late response. I am going to try and work on this again now.

I see the comment above by @corevo asking for test coverage, and I will add that.

Additionally, I see the build failing with an error that seems unrelated to my change, is there something I need to do about this?

'Travis CI - Pull Request' failing - https://github.com/SeleniumHQ/selenium-ide/pull/912/checks?check_run_id=347251806

**Comment by corevo** [comment]
Don't worry about the test failure

**Comment by pierrekin** [comment]
My apologies, we are going to try and get this in this week!

**Comment by pierrekin** [comment]
We have moved this to a new PR, my apologies once again!

**Pull request closed without merging**
