### PR TITLE
Allow single command export via code-export

### PR DESCRIPTION
**Pull request by brandon-piner-aruba**
**Thanks for contributing to the Selenium IDE!**
**A PR well described will help maintainers to quickly review and merge it**

Before submitting your PR, please check our [contributing](https://github.com/SeleniumHQ/selenium-ide/blob/master/CONTRIBUTING.md) guidelines.
Avoid large PRs, help reviewers by making them as simple and short as possible.

### Description
As described in #1254: It would be useful to have emitCommand available in the export-code API. This function should generate the command with given target / value for a selected language / test framework.

### Motivation and Context
We wish to export commands on a per-command basis.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [x] I have read the [contributing](https://github.com/SeleniumHQ/selenium-ide/blob/master/CONTRIBUTING.md) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by brandon-piner-aruba** [comment]
@corevo this is a redo of #912 but with the tests that were requested

**Comment by toddtarsi** [comment]
@brandon-piner-aruba - I certainly can't see the harm in exposing a little bit more modules here, and nice work adding a test and doing all of the export formats! 👍

**Comment by brandon-piner-aruba** [comment]
Thanks @toddtarsi 😄  I would like to get this merged so we can switch back to mainstream branches
Do you know why the build step is waiting?

**Comment by toddtarsi** [comment]
@brandon-piner-aruba - I think it might need authorization to run or something. I could be wrong about that, so I'll check.

**Comment by brandon-piner-aruba** [comment]
@toddtarsi just bumping this PR again in case there is anything you can do. The checks have run and passed now, thank you

**Review by AutomatedTester — APPROVED** [review]

**Comment by AutomatedTester** [comment]
Thank you for your PR!

**Pull request merged**
