### PR TITLE
Migrate selenium-browserbot

### PR DESCRIPTION
**Pull request by corevo**
Migrate the module to UMD, and convert to es2015 class definitions

### CODE REVIEW

**Comment by shs96c** [comment]
Be aware that this is code from the main selenium repo. It may be better to use the original source as that’ll make the process of reintegrating into the main project easier.

**Comment by corevo** [comment]
Indeed, I'm still not sure how to do it, I was planning on cloning and building it?

**Comment by shs96c** [comment]
Ultimately this will be in the monorepo. I’m traveling right now, but will be online for a bit on Monday and then properly on Wednesday. We can plan and plot then. :)

**Comment by samitbadle** [comment]
Won't it make sense to use a new folder in the main repository, say ide3? The old IDE is very tightly coupled with Firefox and it might be a disadvantage moving forward. Is there any reason other than loss of history to not use a new folder?

**Comment by shs96c** [comment]
The new code will be folded back into the main repo (probably as
`//javascript/ide`) when we're closer to an alpha launch (or perhaps
shortly after). Lots of the old code was coupled to Firefox, but there was
a sizeable chunk that wasn't, as it was based on Core, which had to work
everywhere.

**Pull request merged**
